"""
app/core/database.py
--------------------
SQLAlchemy engine, session factory, declarative base, ORM models, and
helper for initialising the database schema.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Generator

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    Index,
    Integer,
    String,
    Text,
    create_engine,
)
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from app.core.config import settings

logger = logging.getLogger(__name__)

# --------------------------------------------------------------------------- #
# Engine & session factory                                                      #
# --------------------------------------------------------------------------- #

# connect_args is only meaningful for SQLite; harmless for other drivers.
_connect_args: dict = (
    {"check_same_thread": False}
    if settings.DATABASE_URL.startswith("sqlite")
    else {}
)

engine = create_engine(
    settings.DATABASE_URL,
    connect_args=_connect_args,
    echo=(settings.APP_ENV == "development"),
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


# --------------------------------------------------------------------------- #
# Declarative base                                                              #
# --------------------------------------------------------------------------- #

class Base(DeclarativeBase):
    pass


# --------------------------------------------------------------------------- #
# ORM Models                                                                    #
# --------------------------------------------------------------------------- #

class Accident(Base):
    """Raw accident record ingested from external data sources."""

    __tablename__ = "accidents"

    id: int = Column(Integer, primary_key=True, index=True)
    latitude: float = Column(Float, nullable=False)
    longitude: float = Column(Float, nullable=False)
    datetime: datetime = Column(DateTime, nullable=False)
    weather: str = Column(String(64), nullable=True)
    road_type: str = Column(String(64), nullable=True)
    lighting: str = Column(String(64), nullable=True)
    vehicle_type: str = Column(String(64), nullable=True)
    severity: str = Column(String(32), nullable=True)      # minor | serious | fatal
    source: str = Column(String(128), nullable=True)


class Hotspot(Base):
    """Pre-computed accident hotspot cluster."""

    __tablename__ = "hotspots"

    id: int = Column(Integer, primary_key=True, index=True)
    latitude: float = Column(Float, nullable=False)
    longitude: float = Column(Float, nullable=False)
    accident_count: int = Column(Integer, default=0)
    severity_index: float = Column(Float, default=0.0)    # 0-1 weighted severity
    radius_m: float = Column(Float, default=500.0)
    risk_level: str = Column(String(32), default="MODERATE")  # LOW|MODERATE|HIGH|CRITICAL


    __table_args__ = (
        Index("ix_hotspots_coords", "latitude", "longitude"),
    )


class Telemetry(Base):
    """Single telemetry ping from a mobile device."""

    __tablename__ = "telemetry"

    id: int = Column(Integer, primary_key=True, index=True)
    device_id: str = Column(String(128), nullable=False, index=True)
    timestamp: datetime = Column(DateTime, nullable=False)
    latitude: float = Column(Float, nullable=False)
    longitude: float = Column(Float, nullable=False)
    speed_kmh: float = Column(Float, default=0.0)
    traffic_level: str = Column(String(32), nullable=True)
    weather_code: str = Column(String(32), nullable=True)
    risk_score: int = Column(Integer, nullable=True)
    risk_level: str = Column(String(32), nullable=True)

    __table_args__ = (
        Index("ix_telemetry_device_time", "device_id", "timestamp"),
        Index("ix_telemetry_location", "latitude", "longitude"),
    )


class Alert(Base):
    """Alert record generated by the risk engine."""

    __tablename__ = "alerts"

    id: int = Column(Integer, primary_key=True, index=True)
    device_id: str = Column(String(128), nullable=False, index=True)
    timestamp: datetime = Column(DateTime, nullable=False)
    alert_type: str = Column(String(64), nullable=False)  # speed | hotspot | weather | crash
    risk_level: str = Column(String(32), nullable=False)
    message: str = Column(Text, nullable=False)
    latitude: float = Column(Float, nullable=True)
    longitude: float = Column(Float, nullable=True)
    acknowledged: bool = Column(Boolean, default=False)

    __table_args__ = (
        Index("ix_alerts_device_time", "device_id", "timestamp"),
        Index("ix_alerts_type_level", "alert_type", "risk_level"),
    )


# --------------------------------------------------------------------------- #
# FastAPI dependency                                                             #
# --------------------------------------------------------------------------- #

def get_db() -> Generator[Session, None, None]:
    """Yield a database session and ensure it is closed afterwards."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# --------------------------------------------------------------------------- #
# Initialisation                                                                #
# --------------------------------------------------------------------------- #

def init_db() -> None:
    """Create all tables if they do not already exist and seed hotspots."""
    import csv
    from pathlib import Path

    logger.info("Initialising database at %s", settings.DATABASE_URL)
    Base.metadata.create_all(bind=engine)

    # Auto-seed hotspots from CSV if table is empty
    with SessionLocal() as db:
        existing_count = db.query(Hotspot).count()
        if existing_count == 0:
            for p in [Path(settings.HOTSPOT_PATH), Path("data/processed/hotspots.csv"), Path("../data/processed/hotspots.csv")]:
                if p.exists():
                    try:
                        with open(p, mode="r", encoding="utf-8") as f:
                            reader = csv.DictReader(f)
                            hs_records = [
                                Hotspot(
                                    latitude=float(row["latitude"]),
                                    longitude=float(row["longitude"]),
                                    accident_count=int(row["accident_count"]),
                                    severity_index=float(row["severity_index"]),
                                    radius_m=float(row.get("radius_m", 500.0)),
                                    risk_level=row.get("risk_level", "MODERATE"),
                                )
                                for row in reader
                            ]
                        db.add_all(hs_records)
                        db.commit()
                        logger.info("Auto-seeded %d hotspots from %s", len(hs_records), p)
                        break
                    except Exception as e:
                        logger.warning("Could not auto-seed hotspots: %s", e)
                        db.rollback()

    logger.info("Database ready.")
